name: rsk_talon
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  dropdown_button2: ^2.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  page_transition: ^2.0.9
  get_it: ^7.6.0
  star_rating: ^0.11.0
  shared_preferences: ^2.1.2
  fluttertoast: ^8.2.2
  flutter_localizations:
        sdk: flutter
  intl: ^0.18.0
  dio: ^5.2.1+1
  permission_handler: ^10.4.1
  google_maps_flutter: ^2.3.1
  translit: ^2.0.1
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/icons/

  # fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200

# flutter launcher icon settings
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

# flutter_native_splash settings
flutter_native_splash:
  image: assets/images/large_logo.png
  background_image: assets/images/splash_bg.png
  fullscreen: true
flutter_intl:
  enabled: true
